Add 'toHast' options to control HAST transformation
mapbox/mdast-react pull request #27
Opened 2016-10-04 09:42 UTC by rhysd

Hello again,

I implemented 'toHast' option, which will be passed to internal `toHAST()` function call.  I added this because I want to control the transformation.
Default value of the option is empty and it doesn't break current behavior :+1:

2016-10-04 19:49 UTC, wooorm requested changes
Looks good, some minor nits.

(Also: testing out GH reviews)

2016-10-04 19:49 UTC, wooorm commented on readme.md
> +    [this API](https://github.com/rhysd/mdast-util-to-hast#api).
Link should be `https://github.com/wooorm/mdast-util-to-hast`

2016-10-04 19:49 UTC, wooorm commented on readme.md
> +    [this API](https://github.com/rhysd/mdast-util-to-hast#api).
`Valid values for the object are `options` parameter of` can maybe be rewritten to ``See `mdast-util-to-hast` for settings`` (shorter, more descriptive)

2016-10-04 19:49 UTC, wooorm commented on test/index.js
> +                }).process(markdown, {}).contents;
Is the no other way to set `allowDangerousHTML` to true here? Doesn’t `sanitize: false` do that already?

2016-10-05 00:00 UTC, rhysd commented on readme.md
> +    [this API](https://github.com/rhysd/mdast-util-to-hast#api).
Ah, I wrongly wrote my fork version URL... I'll fix.

And thank you for proofreading.  I'm not a native English user hence it's very helpful.

2016-10-05 00:01 UTC, rhysd commented on test/index.js
> +                }).process(markdown, {}).contents;
Here, I tested that passing an option to `toHast` configuration does not go wrong.

2016-11-08 14:54 UTC, tmcw commented on test/index.js
> +                }).process(markdown, {}).contents;
That is true - sanitize: false disables [hast-util-sanitize](https://github.com/wooorm/hast-util-sanitize), which has a different set of rules than `allowDangerousHtml` - the latter allows elements verbatim and the former fixes potentially-dangerous properties that are legal in Markdown.

2016-11-08 14:54 UTC, tmcw approved these changes

2016-11-08 15:37 UTC, wooorm approved these changes

2016-11-08 15:37 UTC, wooorm commented
I’m all for it!

2016-11-08 15:40 UTC, merged